name: Python Setup Example

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python --version

      - name: Run the script
        run: python app.py
